#!/usr/bin/env bash

set -e

export AWS_CLI_AUTO_PROMPT=off
# Create our vpc
VPC_ID=$(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--region ap-southeast-1 \
--tag-specifications 'ResourceType=vpc, Tags=[{Key=Name, Value=my-vpc-3}]' \
--query Vpc.VpcId \
--output text)

echo $VPC_ID

#turn on vpc hostname
aws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-hostnames "{\"Value\": true}" --region ap-southeast-1

# Create an IGW
IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--region ap-southeast-1 \
--output text)

echo $IGW_ID

# attach an IGW
aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID --region ap-southeast-1

# Create a new subnet
SUBNET_ID=$(aws ec2 create-subnet \
--vpc-id $VPC_ID \
--cidr-block "172.1.0.0/20" \
--region ap-southeast-1 \
--query Subnet.SubnetId \
--output text)

echo $SUBNET_ID

## auto assign IPv4 addresses
aws ec2 modify-subnet-attribute --subnet-id $SUBNET_ID --map-public-ip-on-launch --region ap-southeast-1

RT_ID=$(aws ec2 describe-route-tables \
  --region ap-southeast-1 \
  --filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
  --query "RouteTables[0].RouteTableId" \
  --output text)

echo $RT_ID

# associate subnet
aws ec2 associate-route-table --route-table-id $RT_ID --subnet-id $SUBNET_ID --region ap-southeast-1

# add a route to route table to our igw
aws ec2 create-route \
--route-table-id $RT_ID \
--destination-cidr-block "0.0.0.0/0" \
--gateway-id $IGW_ID \
--region ap-southeast-1