#!/usr/bin/env bash

set -e

export AWS_CLI_AUTO_PROMPT=off

REGION=ap-southeast-1

if [ -z "$1" ]; then
  echo "Argument not provided."
else
  export VPC_ID=$1
fi

if [ -z "$2" ]; then
  echo "Argument not provided."
else
  export IGW_ID=$2
fi

if [ -z "$3" ]; then
  echo "Argument not provided."
else
  export SUBNET_ID=$3
fi

if [ -z "$4" ]; then
  echo "Argument not provided."
else
  export RT_ID=$4
fi

#delete route
aws ec2 delete-route \
  --route-table-id "$RT_ID" \
  --region $REGION \
  --destination-cidr-block 0.0.0.0/0

#Delete the Subnet
aws ec2 delete-subnet --subnet-id "$SUBNET_ID" --region $REGION
echo "Subnet deleted."

#detach the IGW
aws ec2 detach-internet-gateway \
  --internet-gateway-id "$IGW_ID" \
  --region $REGION \
  --vpc-id "$VPC_ID"
echo "IGW detached."

#delete the IGW
aws ec2 delete-internet-gateway --internet-gateway-id "$IGW_ID" --region $REGION
echo "IGW deleted."

#delete vpc
aws ec2 delete-vpc --vpc-id $VPC_ID --region $REGION