#!/usr/bin/env bash
echo "== list 5 newest buckets with creation dates"

aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0:5] | .[] | "\(.CreationDate) \t \(.Name)"'

echo "..."