AWSTemplateFormatVersion: "2010-09-09"
Description: Launch a simple EC2 for use with testing VPCs
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
  VpcId:
    Type: String
    Default: vpc-069e48814aad31fee
  ImageId:
    Type: String
    Default: ami-05e0d9d655f80bc27
  SubnetId:
    Type: String
    Default: subnet-04492c749806045dc
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      SubnetId: !Ref SubnetId
      InstanceType: !Ref InstanceType
      SecurityGroupIds: 
        - !GetAtt SG.GroupId
  SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      GroupName: String
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VpcId
